# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jiangeng Sun
description: Personal webpage.
baseurl: ""
url: "https://hljmssjg.github.io"
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: 843722226@qq.com

  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/jiangengsun/
    - type: github
      name: GitHub
      link: https://github.com/hljmssjg

toc:
  min_level: 2
  max_level: 3
  no_toc_section_class: no_toc
  list_type: ul
  heading: 目录

# Build settings
markdown: kramdown
highlighter: none

kramdown:
  math_engine: mathjax

sass:
    style: compressed
plugins:
  - jekyll-feed
  - jekyll-toc

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
